### ISSUE TITLE
[BUG] Maven installation fails if the application is not compatible with JDK version in addon

### ISSUE THREAD

**Issue by jmle** [konveyor/tackle2-addon#47]
If the application being analysed is not compilable with the JDK version bundled in the addon, analysis will fail. This can be quite common, as applications to modernise are usually old, and therefore not compatible with newer JDK versions.

In order to download the dependencies, the qaware plugin is recommended, as done [in the analyzer](https://github.com/konveyor/analyzer-lsp/blob/main/provider/internal/java/provider.go#L409).

**Comment by dymurray** [comment]
No longer reproducible in 0.3+
